Repository Alonerz-repo/Alonerz-frontend, pull requests merged in 2022-05, with the labels that each got.

#6 ci / cd test용
  src/App.js
  src/element/button.js
  src/element/index.js
  src/element/input.js
  src/page/caution.js
  src/page/main.js
  src/page/mypage.js
  src/page/partiview.js
Labels: enhancement

#7 의존성 패키지 추가 리덕스 설정
  package.json
  src/App.js
  src/element/button.js
  src/element/grid.js
  src/element/index.js
  src/element/input.js
  src/element/text.js
  src/index.js
  src/page/TestPage.js
  src/page/particreate.js
  src/redux/configureStore.js
  src/redux/modules/image.js
  src/redux/modules/party.js
  src/redux/modules/user.js
  yarn.lock
Labels: enhancement

#49 Text element 수정
  src/components/UserInfo.tsx
  src/elements/Text.tsx
  src/pages/Test.tsx
Labels: enhancement

#57 button 수정건
  public/index.html
  src/App.tsx
  src/components/UserInfo.tsx
  src/elements/Button.tsx
  src/elements/Input.tsx
  src/pages/CreateParty.tsx
  src/pages/KakaoRedirectPage.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/PartyInfo.tsx
  src/pages/Test.tsx
Labels: enhancement

#62 kakao login 기능추가
  package.json
  src/App.tsx
  src/components/UserInfo.tsx
  src/elements/Text.tsx
  src/pages/ConfigList.tsx
  src/pages/KakaoRedirectPage.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/PartyList.tsx
  src/pages/Singup.tsx
  src/store/config.hook.ts
  src/store/config.tsx
  src/store/slices/getUserSlice.tsx
  src/store/slices/userSlice.tsx
  src/utils/api.ts
  src/utils/config.ts
  src/utils/cookie.ts
  yarn.lock
Labels: enhancement

#63 ci/cd 환경변수 추가
  .github/workflows/main.yml
Labels: enhancement

#67 유저 정보 수정 페이지 추가
  src/App.tsx
  src/components/InModifyUser.tsx
  src/components/MyInfo.tsx
  src/elements/Input.tsx
  src/pages/KakaoRedirectPage.tsx
  src/pages/Main.tsx
  src/pages/ModifyUser.tsx
  src/pages/OtherInfo.tsx
  src/pages/Singup.tsx
  src/pages/User.tsx
  src/store/config.tsx
  src/store/slices/getUserSlice.tsx
  src/store/slices/userSlice.tsx
Labels: enhancement

#70 메인 페이지, 파티 리스트 페이지 목록 조회 api 연결
  src/components/Card.tsx
  src/components/MyInfo.tsx
  src/pages/ConsentForm.tsx
  src/pages/Main.tsx
  src/pages/OtherInfo.tsx
  src/pages/PartyList.tsx
  src/pages/User.tsx
  src/store/config.tsx
  src/store/slices/PartyListSlice.tsx
  src/store/slices/userSlice.tsx
Labels: enhancement

#79 기능 추가
  src/App.tsx
  src/assets/Icon/1.png
  src/assets/Icon/10.png
  src/assets/Icon/11.png
  src/assets/Icon/12.png
  src/assets/Icon/13.png
  src/assets/Icon/14.png
  src/assets/Icon/15.png
  src/assets/Icon/16.png
  src/assets/Icon/17.png
  src/assets/Icon/18.png
  src/assets/Icon/19.png
  src/assets/Icon/2.png
  src/assets/Icon/20.png
  src/assets/Icon/21.png
  src/assets/Icon/22.png
  src/assets/Icon/23.png
  src/assets/Icon/24.png
  src/assets/Icon/25.png
  src/assets/Icon/26.png
  src/assets/Icon/27.png
  src/assets/Icon/28.png
  src/assets/Icon/29.png
  src/assets/Icon/3.png
  src/assets/Icon/30.png
  src/assets/Icon/31.png
  src/assets/Icon/32.png
  src/assets/Icon/4.png
  src/assets/Icon/5.png
  src/assets/Icon/6.png
  src/assets/Icon/7.png
  src/assets/Icon/8.png
  src/assets/Icon/9.png
  src/assets/Icon/index.ts
  src/assets/header/1.svg
  src/assets/header/chat.png
  src/assets/header/home.png
  src/assets/header/index.ts
  src/assets/header/setting.png
  src/axios/partyAxios.tsx
  src/axios/userAxios.tsx
  src/components/Header.tsx
  src/components/InModifyUser.tsx
  src/components/Logout.tsx
  src/components/MyInfo.tsx
  src/components/ProfileBox.tsx
  src/elements/Button.tsx
  src/elements/Text.tsx
  src/pages/BlockList.tsx
  src/pages/ConfigList.tsx
  src/pages/FollowList.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/ModifyUser.tsx
  src/pages/Test.tsx
  src/pages/User.tsx
  src/store/slices/getUserSlice.tsx
  src/store/slices/userSlice.tsx
  src/utils/api.ts
Labels: enhancement

#91 작업물 주석 처리
  src/assets/header/index.ts
  src/axios/authAxios.tsx
  src/axios/loginAxios.tsx
  src/axios/userAxios.tsx
  src/components/Comment.tsx
  src/components/MyInfo.BtnAction.tsx
  src/components/MyInfo.GridTxt.tsx
  src/components/MyInfo.tsx
  src/components/ProfileBox.tsx
  src/elements/Input.tsx
  src/elements/Text.tsx
  src/pages/KakaoRedirectPage.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/ModifyUser.tsx
  src/pages/ProflieEdit.tsx
  src/pages/Test.tsx
  src/pages/User.tsx
  src/store/slices/userSlice.tsx
  src/useCustom/useAuth.tsx
  src/useCustom/useFollow.tsx
  src/useCustom/useUser.tsx
  src/utils/career.ts
Labels: documentation

#93 댓글 CRUD작업 완료
  src/axios/commentAxios.tsx
  src/components/Comment.tsx
  src/components/MyInfo.tsx
  src/elements/Text.tsx
  src/pages/PartyInfo.tsx
Labels: enhancement

#106 최원영 feat : 모달창 UI 구현
  src/components/AlertModal.tsx
  src/components/ConfirmModal.tsx
  src/pages/ProflieEdit.tsx
  src/pages/User.tsx
Labels: enhancement

#107 최원영 feat : 사용자 프로필 정보 수정 시 모달창 적용
  src/components/AlertModal.tsx
  src/pages/ModifyUser.tsx
Labels: enhancement

#108 최원영 : GroupDetailPage 구현 및 Interface & Type 정의
  old/Comment.mainCmt.tsx
  old/Comment.tsx
  old/PartyInfo.tsx
  src/App.tsx
  src/axios/commentAxios.tsx
  src/axios/groupAxios.tsx
  src/components/Comment.tsx
  src/components/KakaoMap.tsx
  src/elements/Button.tsx
  src/elements/Image.tsx
  src/elements/Input.tsx
  src/pages/GroupDetailPage/GroupChildComment.tsx
  src/pages/GroupDetailPage/GroupChildComments.tsx
  src/pages/GroupDetailPage/GroupDetail.tsx
  src/pages/GroupDetailPage/GroupMember.tsx
  src/pages/GroupDetailPage/GroupMembers.tsx
  src/pages/GroupDetailPage/GroupParentComment.tsx
  src/pages/GroupDetailPage/GroupParentComments.tsx
  src/pages/GroupDetailPage/index.tsx
  src/pages/GroupDetailPage/interface.ts
  src/pages/PartyList.tsx
  src/utils/asset.ts
Labels: enhancement

#110 최원영 feat : 댓글 수정 API, 디자인 일부 적용, 미사용 코드 정리
  old/Comment.subCmt.tsx
  src/assets/data/categories.json
  src/axios/commentAxios.tsx
  src/components/Header.tsx
  src/elements/Text.tsx
  src/index.css
  src/pages/GroupDetailPage/GroupChildComment.tsx
  src/pages/GroupDetailPage/GroupChildComments.tsx
  src/pages/GroupDetailPage/GroupDetail.tsx
  src/pages/GroupDetailPage/GroupMembers.tsx
  src/pages/GroupDetailPage/GroupParentComment.tsx
  src/pages/GroupDetailPage/GroupParentComments.tsx
  src/pages/GroupDetailPage/index.tsx
  src/pages/GroupDetailPage/interface.ts
  src/pages/GroupDetailPage/styled.tsx
  src/utils/asset.ts
Labels: enhancement

#111 유저 프로필 팔로우 모달 적용
  old/Comment.mainCmt.tsx
  old/Comment.subCmt.tsx
  old/Comment.tsx
  old/PartyInfo.tsx
  src/axios/boardAxios.tsx
  src/axios/userAxios.tsx
  src/components/Follow.tsx
  src/components/MyInfo.tsx
  src/components/ProfileBox.bottom.tsx
  src/components/ProfileBox.top.tsx
  src/exception/user.exception.ts
  src/pages/FollowList.tsx
  src/pages/GroupDetailPage/GroupChildComments.tsx
  src/pages/GroupDetailPage/GroupParentComment.tsx
  src/pages/Main.tsx
  src/pages/ModifyUser.tsx
  src/pages/ProflieEdit.tsx
  src/pages/User.tsx
  src/store/slices/characterSlice.tsx
  src/useCustom/useFollow.tsx
  src/useCustom/useUser.tsx
  src/utils/asset.ts
Labels: enhancement

#112 최원영 feat : 모달창 적용 및 예외 처리
  src/App.tsx
  src/axios/groupAxios.tsx
  src/components/AlertModal.tsx
  src/components/ConfirmModal.tsx
  src/pages/GroupDetailPage/GroupChildComment.tsx
  src/pages/GroupDetailPage/GroupChildComments.tsx
  src/pages/GroupDetailPage/GroupDetail.tsx
  src/pages/GroupDetailPage/GroupMember.tsx
  src/pages/GroupDetailPage/GroupMembers.tsx
  src/pages/GroupDetailPage/GroupParentComment.tsx
  src/pages/GroupDetailPage/exception.ts
  src/pages/GroupDetailPage/index.tsx
  src/pages/GroupDetailPage/styled.tsx
Labels: enhancement

#115 리액트 훅 폼을 이용한 유저 수정 부분 예외처리
  package.json
  src/assets/Character/3.png
  src/assets/Character/4.png
  src/assets/Character/index.ts
  src/components/MyInfo.tsx
  src/components/ProfileBox.bottom.tsx
  src/components/ProfileBox.top.tsx
  src/exception/user.exception.ts
  src/pages/Main.tsx
  src/pages/ModifyUser.tsx
  src/pages/ProflieEdit.tsx
  src/pages/Test.tsx
  yarn.lock
Labels: enhancement

#116 최원영 feat : 온보딩 페이지 구현 및 build 명령어 수정
  package.json
  public/logo.png
  public/logo192.png
  public/logo256.png
  public/logo512.png
  src/App.tsx
  src/assets/data/onboards.json
  src/assets/images/onboards/01.png
  src/assets/images/onboards/02.png
  src/assets/images/onboards/03.png
  src/assets/images/onboards/04.png
  src/components/Card.tsx
  src/components/Header.tsx
  src/index.css
  src/pages/GroupDetailPage/GroupChildComments.tsx
  src/pages/GroupDetailPage/GroupDetail.tsx
  src/pages/OnBoardingPage/OnBoadingCard.tsx
  src/pages/OnBoardingPage/OnBoadingDots.tsx
  src/pages/OnBoardingPage/index.tsx
  src/pages/OnBoardingPage/styled.tsx
  src/utils/asset.ts
  src/utils/images.ts
Labels: enhancement

#119 최원영 feat : 메인 페이지 구현
  old/Main.tsx
  src/App.tsx
  src/axios/groupAxios.tsx
  src/components/Header.tsx
  src/components/ProfileBox.top.tsx
  src/pages/GroupDetailPage/index.tsx
  src/pages/GroupDetailPage/styled.tsx
  src/pages/MainPage/TodayOtherGroupCard.tsx
  src/pages/MainPage/TodayOwnGroupCard.tsx
  src/pages/MainPage/TodayOwnGroupCards.tsx
  src/pages/MainPage/images/arrow-left.svg
  src/pages/MainPage/images/arrow-right.svg
  src/pages/MainPage/images/dinner.png
  src/pages/MainPage/images/index.ts
  src/pages/MainPage/images/lunch.png
  src/pages/MainPage/index.tsx
  src/pages/MainPage/styled.tsx
  src/pages/OnBoardingPage/index.tsx
  src/pages/ProflieEdit.tsx
  yarn.lock
Labels: enhancement

#157 최원영 feat : 내 정보 수정 페이지 기능 구현
  src/axios/userAxios.tsx
  src/components/AppHeader/README.md
  src/components/AppHeader/index.tsx
  src/pages/ModifyUser.tsx
  src/pages/ProfileEditPage/index.tsx
Labels: documentation, enhancement

#163 참여가능이 가득 찼을 때 예외 처리
  src/index.css
  src/pages/GroupDetailPage/exception.ts
  src/pages/GroupDetailPage/index.tsx
  src/pages/ProfileEditPage/index.tsx
Labels: enhancement

#164 최원영 feat : 스티커 이미지 추가 및 VueJS 아이콘 180도 회전하도록 svg 수정
  src/assets/category/data.json
  src/assets/sticker/01.svg
  src/assets/sticker/02.svg
  src/assets/sticker/03.svg
  src/assets/sticker/04.svg
  src/assets/sticker/05.svg
  src/assets/sticker/06.svg
  src/assets/sticker/07.svg
  src/assets/sticker/08.svg
  src/assets/sticker/09.svg
  src/assets/sticker/10.svg
  src/assets/sticker/11.svg
  src/assets/sticker/12.svg
  src/assets/sticker/13.svg
  src/assets/sticker/14.svg
  src/assets/sticker/15.svg
  src/assets/sticker/16.svg
  src/assets/sticker/17.svg
  src/assets/sticker/18.svg
  src/assets/sticker/19.svg
  src/assets/sticker/20.svg
  src/assets/sticker/21.svg
  src/assets/sticker/22.svg
  src/assets/sticker/23.svg
  src/assets/sticker/24.svg
  src/assets/sticker/25.svg
  src/assets/sticker/26.svg
  src/assets/sticker/27.svg
  src/assets/sticker/28.svg
  src/assets/sticker/29.svg
  src/assets/sticker/30.svg
  src/assets/sticker/31.svg
  src/assets/sticker/32.svg
  src/assets/sticker/33.svg
  src/assets/sticker/34.svg
  src/assets/sticker/35.svg
  src/assets/sticker/36.svg
  src/assets/sticker/37.svg
  src/assets/sticker/index.ts
Labels: enhancement

#171 컨텐츠가 없는 경우 렌더링할 컴포넌트 구현, 팔로잉 / 팔로워 / 차단 기능 및 페이지 구현 완료
  src/App.tsx
  src/axios/userAxios.tsx
  src/components/EmptyContent/README.md
  src/components/EmptyContent/images/empty.svg
  src/components/EmptyContent/index.tsx
  src/components/Header.tsx
  src/components/MyInfo.tsx
  src/components/UserCard/OtherFollowerButtonGroup.tsx
  src/components/UserCard/OtherFollowingButtonGroup.tsx
  src/components/UserCard/OwnBlockButtonGroup.tsx
  src/components/UserCard/OwnFollowerButtonGroup.tsx
  src/components/UserCard/OwnFollowingButtonGroup.tsx
  src/components/UserCard/README.md
  src/components/UserCard/index.tsx
  src/components/UserCard/styled.tsx
  src/components/UserCardList/OtherFollowerList.tsx
  src/components/UserCardList/OtherFollowingList.tsx
  src/components/UserCardList/OwnBlockList.tsx
  src/components/UserCardList/OwnFollowerList.tsx
  src/components/UserCardList/OwnFollowingList.tsx
  src/components/UserCardList/README.md
  src/components/UserCardList/index.tsx
  src/components/UserCardList/styled.tsx
  src/pages/ConfigList.tsx
  src/pages/GroupDetailPage/GroupMember.tsx
  src/pages/GroupListPage/index.tsx
  src/pages/UserListPage/UserCard/OtherFollowerButtonGroup.tsx
  src/pages/UserListPage/UserCard/OtherFollowingButtonGroup.tsx
  src/pages/UserListPage/UserCard/OwnBlockButtonGroup.tsx
  src/pages/UserListPage/UserCard/OwnFollowerButtonGroup.tsx
  src/pages/UserListPage/UserCard/OwnFollowingButtonGroup.tsx
  src/pages/UserListPage/UserCard/README.md
  src/pages/UserListPage/UserCard/index.tsx
  src/pages/UserListPage/UserCard/styled.tsx
  src/pages/UserListPage/UserCardList/OtherFollowerList.tsx
  src/pages/UserListPage/UserCardList/OtherFollowingList.tsx
  src/pages/UserListPage/UserCardList/OwnBlockList.tsx
  src/pages/UserListPage/UserCardList/OwnFollowerList.tsx
  src/pages/UserListPage/UserCardList/OwnFollowingList.tsx
  src/pages/UserListPage/UserCardList/README.md
  src/pages/UserListPage/UserCardList/index.tsx
  src/pages/UserListPage/UserCardList/styled.tsx
  src/pages/UserListPage/index.tsx
Labels: enhancement

#173 기능 추가 선택시 표시기능
  src/App.tsx
  src/axios/boardAxios.tsx
  src/components/MyInfo.tsx
  src/components/ProfileBox.bottom.tsx
  src/components/ProfileBox.top.tsx
  src/pages/ChatList.tsx
  src/pages/Chatting.tsx
  src/pages/MainPage/index.tsx
  src/pages/ProfileEditPage/index.tsx
  src/pages/ProfileEditPage/styled.tsx
  src/pages/ProflieEdit.tsx
  src/store/config.tsx
  src/store/slices/changeSlice.tsx
Labels: enhancement
